version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha
      MONGO_INITDB_DATABASE: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha
      ME_CONFIG_MONGODB_URL: mongodb://root:senha@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongo

  stable-diffusion-api:
    build:
      context: ./api-ia/backend-files
      dockerfile: images/Dockerfile
    container_name: stable-diffusion-api
    ports:
      - "9001:9001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./api-ia/backend-files/images:/images
      - ./api-ia/backend-files/images/webservice.py:/app/webservice.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  grupo-1-service:
    build:
      context: ./web/grupo-1
      dockerfile: Dockerfile
    container_name: grupo-1-container
    ports:
      - "8001:8081"
    volumes:
      - ./web/grupo-1:/app

  grupo-1-api:
    build:
      context: ./api-grupo-1
      dockerfile: Dockerfile
    container_name: grupo-1-api-container
    ports:
      - "3001:3001"
    volumes:
      - ./api-grupo-1:/app
    environment:
      - MONGODB_URL=mongodb://root:senha@mongo:27017/admin

  whisper-webservice:
    image: 'onerahmet/openai-whisper-asr-webservice:latest'
    container_name: whisper-webservice
    ports:
      - '9002:9000'
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
